name: "Generate Offplan Posts"

on:
  
  workflow_dispatch:

jobs:
  generate_offplan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pillow cairosvg requests

      - name: Generate offplan posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_offplan_posts.py

      - name: Commit and push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add graphics_offplan/*.png
          git commit -m "Automatisch generierte Off-Plan Immobilienposts" || echo "Nichts zu committen"
          git pull --rebase
          git push
