name: Update Dubai Property Projects

on:
  schedule:
    # - cron: '0 5 * * *'    # 09:00 Dubai-Zeit
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser pytz openai requests beautifulsoup4 playwright
          playwright install chromium

      - name: Run Real Estate News Scraper
        run: python update_realestate.py

      - name: Debug file output
        run: |
          echo "✅ Listing news directory content:"
          ls -lh news
          echo "✅ File preview:"
          head -n 40 news/dubai-neubauprojekte-news.txt || echo "❌ Datei nicht vorhanden"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news/*.txt
          git commit -m "Daily Update Dubai Projects" || echo "No changes to commit"
          git push
