name: Manuelles Update Dubai Real Estate News

on:
  workflow_dispatch:  # Nur manuell auslösbar

jobs:
  update-news:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser pytz openai requests beautifulsoup4

      - name: Run news script
        run: python dein_skriptname.py  # <-- Hier bitte deinen Dateinamen einsetzen (z.B. dubai_news_scraper.py)

      - name: Debug file output
        run: |
          echo "✅ Listing news directory content:"
          ls -lh news
          echo "✅ File preview:"
          head -n 40 news/dubai-neubauprojekte-news.txt || echo "❌ Datei nicht vorhanden"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news/dubai-neubauprojekte-news.txt
          git commit -m "Manuelles Update Dubai Real Estate News" || echo "No changes to commit"
          git push
